import ../Types

{.push cdecl, importc.}

proc LLVMAddAggressiveDCEPass*(PM: LLVMPassManagerRef)
proc LLVMAddBitTrackingDCEPass*(PM: LLVMPassManagerRef)
proc LLVMAddAlignmentFromAssumptionsPass*(PM: LLVMPassManagerRef)
proc LLVMAddCFGSimplificationPass*(PM: LLVMPassManagerRef)
proc LLVMAddDeadStoreEliminationPass*(PM: LLVMPassManagerRef)
proc LLVMAddScalarizerPass*(PM: LLVMPassManagerRef)
proc LLVMAddMergedLoadStoreMotionPass*(PM: LLVMPassManagerRef)
proc LLVMAddGVNPass*(PM: LLVMPassManagerRef)
proc LLVMAddNewGVNPass*(PM: LLVMPassManagerRef)
proc LLVMAddIndVarSimplifyPass*(PM: LLVMPassManagerRef)
proc LLVMAddInstructionCombiningPass*(PM: LLVMPassManagerRef)
proc LLVMAddJumpThreadingPass*(PM: LLVMPassManagerRef)
proc LLVMAddLICMPass*(PM: LLVMPassManagerRef)
proc LLVMAddLoopDeletionPass*(PM: LLVMPassManagerRef)
proc LLVMAddLoopIdiomPass*(PM: LLVMPassManagerRef)
proc LLVMAddLoopRotatePass*(PM: LLVMPassManagerRef)
proc LLVMAddLoopRerollPass*(PM: LLVMPassManagerRef)
proc LLVMAddLoopUnrollPass*(PM: LLVMPassManagerRef)
proc LLVMAddLoopUnswitchPass*(PM: LLVMPassManagerRef)
proc LLVMAddMemCpyOptPass*(PM: LLVMPassManagerRef)
proc LLVMAddPartiallyInlineLibCallsPass*(PM: LLVMPassManagerRef)
proc LLVMAddLowerSwitchPass*(PM: LLVMPassManagerRef)
proc LLVMAddPromoteMemoryToRegisterPass*(PM: LLVMPassManagerRef)
proc LLVMAddReassociatePass*(PM: LLVMPassManagerRef)
proc LLVMAddSCCPPass*(PM: LLVMPassManagerRef)
proc LLVMAddScalarReplAggregatesPass*(PM: LLVMPassManagerRef)
proc LLVMAddScalarReplAggregatesPassSSA*(PM: LLVMPassManagerRef)
proc LLVMAddScalarReplAggregatesPassWithThreshold*(PM: LLVMPassManagerRef; Threshold: cint)
proc LLVMAddSimplifyLibCallsPass*(PM: LLVMPassManagerRef)
proc LLVMAddTailCallEliminationPass*(PM: LLVMPassManagerRef)
proc LLVMAddConstantPropagationPass*(PM: LLVMPassManagerRef)
proc LLVMAddDemoteMemoryToRegisterPass*(PM: LLVMPassManagerRef)
proc LLVMAddVerifierPass*(PM: LLVMPassManagerRef)
proc LLVMAddCorrelatedValuePropagationPass*(PM: LLVMPassManagerRef)
proc LLVMAddEarlyCSEPass*(PM: LLVMPassManagerRef)
proc LLVMAddEarlyCSEMemSSAPass*(PM: LLVMPassManagerRef)
proc LLVMAddLowerExpectIntrinsicPass*(PM: LLVMPassManagerRef)
proc LLVMAddTypeBasedAliasAnalysisPass*(PM: LLVMPassManagerRef)
proc LLVMAddScopedNoAliasAAPass*(PM: LLVMPassManagerRef)
proc LLVMAddBasicAliasAnalysisPass*(PM: LLVMPassManagerRef)

{.pop.}
